# Generated by Django 6.0 on 2026-01-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Pelanggan')),
                ('no_hp', models.CharField(max_length=20, verbose_name='Nomor HP/WA')),
                ('alamat', models.TextField(verbose_name='Alamat Lengkap')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('foto_lokasi', models.ImageField(blank=True, null=True, upload_to='foto_pelanggan/', verbose_name='Foto Depo/Rumah')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Data Pelanggan',
            },
        ),
    ]
